const NotificationType = {

    GENERAL: "GENERAL",

    APPOINTMENT_BOOKED: "APPOINTMENT_BOOKED",

    APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",

    APPOINTMENT_RESCHEDULED: "APPOINTMENT_RESCHEDULED",

    APPOINTMENT_REMINDER: "APPOINTMENT_REMINDER",

    APPOINTMENT_NO_SHOW: "APPOINTMENT_NO_SHOW",

    FOLLOWUP_REMINDER: "FOLLOWUP_REMINDER",

    PRESCRIPTION_AVAILABLE: "PRESCRIPTION_AVAILABLE",

    MEDICATION_REMINDER: "MEDICATION_REMINDER",

    PRE_VISIT_SUMMARY_READY: "PRE_VISIT_SUMMARY_READY",

    POST_VISIT_SUMMARY_READY: "POST_VISIT_SUMMARY_READY"

};

module.exports = NotificationType;